# Started Learning Numpy

In [1]:
import numpy as np

In [2]:
arr = np.arange(1000)

In [3]:
np.array([1,2,5,19,32,0])

array([ 1,  2,  5, 19, 32,  0])

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


# Numpy Attributes

### shape, ndim, dtype, itemsize are some of the attributes

In [5]:
arr1=np.array(([3,5,7,8],[23,45,1,19]))

In [6]:
arr1.shape

(2, 4)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.shape=(4,2)

In [9]:
arr1

array([[ 3,  5],
       [ 7,  8],
       [23, 45],
       [ 1, 19]])

In [10]:
arr1.shape=(2,2,2)
arr1.dtype='int32'

In [11]:
arr1

array([[[ 3,  0,  5,  0],
        [ 7,  0,  8,  0]],

       [[23,  0, 45,  0],
        [ 1,  0, 19,  0]]], dtype=int32)

In [14]:
arr2=arr1.reshape((1,16))

In [15]:
arr2

array([[ 3,  0,  5,  0,  7,  0,  8,  0, 23,  0, 45,  0,  1,  0, 19,  0]],
      dtype=int32)

In [16]:
arr2.ndim

2

In [17]:
arr2.itemsize

4

In [22]:
arr3=np.array([2,45,11],dtype='float64')
arr3

array([ 2., 45., 11.])

# To create an empty array

In [23]:
arr4=np.zeros((4,6))
arr4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((3,4,5),dtype='int64')#Garbage value

array([[[ 93891198000634,               0, 140611252087792,
         140611252088048, 140611254443120],
        [140611252162288, 140611250138032, 140611241685632,
         140611254442928, 140611254532720],
        [140611250186736, 140611243400368, 140611249292272,
         140611241671600, 140611241671728],
        [140611241671792, 140611241671856, 140611253433968,
         140611254615152, 140611254636608]],

       [[140611242386096, 140611241654672, 140611241653008,
         140611254655792, 140611254656176],
        [140611254655920, 140611254654576, 140611241664832,
         140611265075392, 140611265075552],
        [140611250314800, 140611241686016, 140611241671984,
         140611241672048, 140611253408624],
        [140611254183328, 140611265075488, 140611251958192,
         140611253217584, 140611253436144]],

       [[140611253436080, 140611265075360, 140611252532656,
         140611254801968, 140611253348272],
        [140611254810288, 140611254430128, 140611254422448,


In [26]:
np.ones((3,4,5),dtype='int64')

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

# Basic Operations

In [31]:
arr1=np.array([23,4,6])
arr1

array([23,  4,  6])

In [32]:
arr3

array([ 2., 45., 11.])

In [33]:
arr1*arr3

array([ 46., 180.,  66.])

In [34]:
arr1+arr3

array([25., 49., 17.])

In [35]:
1/arr1

array([0.04347826, 0.25      , 0.16666667])

In [36]:
arr3+7

array([ 9., 52., 18.])

In [37]:
arr1+0.5

array([23.5,  4.5,  6.5])

In [38]:
arr1/arr3

array([11.5       ,  0.08888889,  0.54545455])

In [39]:
arr1**arr3

array([5.29000000e+02, 1.23794004e+27, 3.62797056e+08])