# Slicing

In [1]:
import numpy as np

In [2]:
arr1=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
arr1[1,2]

7

In [3]:
arr2=arr1[0:2]
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr3=arr2[0][2:4]
arr3

array([3, 4])

In [5]:
arr2[1][1]

6

# Note that slicing creates a view and not a copy of the array

In [6]:
arr3[1]=24
arr3

array([ 3, 24])

In [7]:
arr1

array([[ 1,  2,  3, 24],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
arr2

array([[ 1,  2,  3, 24],
       [ 5,  6,  7,  8]])

# More Slicing and Dicing

In [11]:
arr3

array([ 3, 24])

In [12]:
arr3[2]=45

IndexError: index 2 is out of bounds for axis 0 with size 2

In [13]:
arr2[0]

array([ 1,  2,  3, 24])

In [16]:
arr2[0][0:3:2]

array([1, 3])

In [17]:
arr2[0][::-1]

array([24,  3,  2,  1])