# More Numpy Functions

In [1]:
# arange() and reshape() already seen

In [2]:
import numpy as np

In [3]:
arr=np.array([23,12,1,27,101])
arr

array([ 23,  12,   1,  27, 101])

In [4]:
np.sort(arr)

array([  1,  12,  23,  27, 101])

In [6]:
np.argsort(arr)
#gives original index of each element of sorted array

array([2, 1, 0, 3, 4])

In [7]:
np.max(arr)

101

In [8]:
np.argmax(arr)
#index of max element

4

In [9]:
np.argmin(arr)

2

In [10]:
#it by default uses axis = n-1
#we can argsort according to axis similar to other functions